### ISSUE TITLE
Crash after updating to 0.2.0

### ISSUE THREAD

**Issue by Shabinder** [Kotlin/kotlinx-datetime#112]
`java.lang.NoSuchMethodError: No virtual method elapsedNow-UwyO8pc()D in class Lkotlin/time/TimeMark; or its super classes (declaration of 'kotlin.time.TimeMark' appears in /data/app/~~I_OMx5UaYUOjrefCz8Lr9Q=`

**Comment by Shabinder** [comment]
Not related to this lib , sorry
