### ISSUE TITLE
Duplicate monthNumber in format factory after migrate to 0.7.1

### ISSUE THREAD

**Issue by TakanashiHitomi** [Kotlin/kotlinx-datetime#566]
Hello,
After I migrate lib from 0.6.2 to 0.7.1, I found some crash in my application.
Seems there are 2 monthNumber in my format, but there should be only one.
And this crash is not shown every time, just several Android 11 and 8 devices.

I test these codes in emulator for several times, but none of them show this bug.
Please notify me if anything wrong in my code.

Thanks!

```log
Fatal Exception: java.lang.IllegalArgumentException: At most one variable-length numeric field in a row is allowed, but got several: [monthNumber, monthNumber]. Parsing is undefined: for example, with variable-length month number and variable-length day of month, '111' can be parsed as Jan 11th or Nov 1st.
       at kotlinx.datetime.internal.format.parser.NumberSpanParserOperation.<init>(ParserOperation.kt:56)
       at kotlinx.datetime.internal.format.parser.ParserKt.concat$simplify(Parser.kt:96)
       at kotlinx.datetime.internal.format.parser.ParserKt.concat(Parser.kt:125)
       at kotlinx.datetime.internal.format.ConcatenatedFormatStructure.parser(FormatStructure.kt:233)
       at kotlinx.datetime.internal.format.CachedFormatStructure.<init>(FormatStructure.kt:248)
       at kotlinx.datetime.format.AbstractDateTimeFormatBuilder.build(DateTimeFormatBuilder.kt:476)
       at kotlinx.datetime.format.DateTimeComponents$Companion.Format(DateTimeComponents.kt:59)
       at [my.package.name].TimeFormatKt.dateTimeFormat(TimeFormat.kt:50)
```

```kt
// TimeFormat.kt
fun Instant.dateTimeFormat(): String {
    val targetDateTime = this.toLocalDateTime(TimeZone.currentSystemDefault())
    val currentDateTime = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())

    val isSameYear = targetDateTime.year == currentDateTime.year
    val isSameDate = isSameYear &&
            targetDateTime.monthNumber == currentDateTime.monthNumber &&
            targetDateTime.dayOfMonth == currentDateTime.dayOfMonth

    // crash report here
    val format = DateTimeComponents.Format {
        if (isSameDate) {
            char(' ')
            hour(); char(':'); minute()
        } else {
            monthNumber(); char('/'); dayOfMonth(); if (isSameYear.not()) {
                char('/'); year()
            }
        }
    }

    return format(format)
}

// Display.kt
Text(
    text = item.lastMessageDate?.dateTimeFormat() ?: "",
    style = MaterialTheme.typography.bodySmall,
    color = MaterialTheme.colorScheme.descriptionText,
)
```

**Comment by fzhinkin** [comment]
@TakanashiHitomi is there anything specific about a combination of a current timezone, currentDateTime and an instant the `dateTimeFormat` is invoked on? Would it be possible for you to extract this information from an app when the failure is happening?
At the first glance, I don't see how a formatter construction may trigger the exception, but maybe I will be lucky enough to reproduce it given exactly the same inputs you have.

**Comment by fzhinkin** [comment]
@TakanashiHitomi, do you use R8 to minify and/or obfuscate the app? My most prominent guess so far is that R8 transforms the library in a way it causes the issue. Perhaps, `-keep class kotlinx.datetime.**.* { *; }` rule would help.

**Comment by dkhalanskyjb** [comment]
The solution you ended up with is more idiomatic, as this way, work is not repeated unnecessarily: each format is only constructed once and then reused when `Instant` values are formatted in the future.

That said, the original solution is perfectly valid, too, so it's worth it to report this problem to Android. I suspect it's something on their side, given that the problem is localized to specific device configurations (which `kotlinx-datetime` should not be affected by).

**Comment by dkhalanskyjb** [comment]
Closing since it doesn't look like a problem that can be fixed in our library, but if it turns out we can do something about this, please ping us, and we'll reopen the issue.
