### ISSUE TITLE
Tests don't compile with Kotlin 2.1.20

### ISSUE THREAD

**Issue by martinkretzschmar** [Kotlin/kotlinx-datetime#504]
The tests that

```
import kotlinx.datetime.*
import kotlin.time.*
```

do not compile because there are now both `kotlinx.datetime` and `kotlin.time` versions of `Clock` and `Instant`:

```
ClockTimeSourceTest.kt:26: error: overload resolution ambiguity between candidates:
interface Clock : Any
interface Clock : Any
        val timeSource = Clock.System.asTimeSource()
                         ^^^^^
```

**Comment by dkhalanskyjb** [comment]
You probably mean `kotlinx.datetime`, not `kotlinx.time`, right? Yes, that's true, the standard library now has `Clock` and `Instant`. You are advised to avoid star imports, or you will encounter such issues when some library adds a new API.

**Comment by martinkretzschmar** [comment]
> You probably mean `kotlinx.datetime`, not `kotlinx.time`, right?

Yes, thanks. Edited.

> Yes, that's true, the standard library now has `Clock` and `Instant`. You are advised to avoid star imports, or you will encounter such issues when some library adds a new API.

I mean there are tests in this repository that have this problem
