### ISSUE TITLE
Updating to 0.4.1 causes compilation issue

### ISSUE THREAD

**Issue by dmitry-stakhov** [Kotlin/kotlinx-datetime#313]
After upgrading from 0.4.0 to 0.4.1 in our KMP library, the Android app consuming our KMP library starts to produce the compilation error.

```
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/versions/9/previous-compilation-data.bin' from inputs:
      - /Users/username/.gradle/caches/transforms-3/2e031c7d51fad55be6877abccf6ede0e/transformed/jetified-kotlinx-datetime-jvm-0.4.1.jar
      - /Users/username/.gradle/caches/transforms-3/2ac55ab61b2787a526d3ea1a79904898/transformed/jetified-atomicfu-jvm-0.22.0.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/8.1/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information
```

Found workaround:
Add the next code in app build.gradle.kts:
```
packaging {
    resources.excludes.add("META-INF/versions/9/previous-compilation-data.bin")
}
```

**Comment by dkhalanskyjb** [comment]
Duplicate of https://github.com/Kotlin/kotlinx-datetime/issues/304
